apiVersion: v2
name: kubemod
description: KubeMod is a universal Kubernetes mutating operator.
version: 0.2.3
appVersion: "0.13.0"
kubeVersion: ">= 1.16.0-0"
home: https://github.com/kubemod/kubemod
sources:
  - https://github.com/kubemod/kubemod
  - https://github.com/kubemod/kubemod-helm
maintainers:
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: vassilvk
