apiVersion: v2
name: kubemod
description: KubeMod is a universal Kubernetes mutating operator.
version: 0.4.1
appVersion: "v0.19.1"
kubeVersion: ">= 1.16.0-0"
home: https://github.com/kubemod/kubemod
sources:
  - https://github.com/kubemod/kubemod
  - https://github.com/kubemod/kubemod-helm
maintainers:
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: vassilvk
  - name: abirsigron
