apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kubemod.fullname" . }}-crt-cron-job
  labels:
    {{- include "kubemod.labels" . | nindent 4 }}
spec:
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          {{- if .Values.priorityClassName }}
          priorityClassName: {{ .Values.priorityClassName | quote }}
          {{- end }}
          containers:
          - command:
            - /bin/sh
            - -c
            - ./cert-renew.sh
            image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
            name: kubemod-crt
          restartPolicy: Never
          serviceAccountName: {{ include "kubemod.serviceAccountName" . }}-crt
  schedule: 0 0 1 * *