apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubemod.fullname" . }}-crt-job
  labels:
    {{- include "kubemod.labels" . | nindent 4 }}
spec:
  backoffLimit: 4
  template:
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
      - command:
        - /bin/sh
        - -c
        - ./cert-renew.sh
        image: kubemod/kubemod-crt:v1.3.0
        name: kubemod-crt
      restartPolicy: Never
      serviceAccountName: {{ include "kubemod.serviceAccountName" . }}-crt