apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubemod.fullname" . }}-crt-patch-webhooks
  labels:
    {{- include "kubemod.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 4
  template:
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
      - command:
        - /kubemod-crt/cert-patch-webhooks.sh
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        name: kubemod-crt
        volumeMounts:
          - mountPath: /tmp/ca
            name: ca
            readOnly: true
      restartPolicy: Never
      serviceAccountName: {{ include "kubemod.serviceAccountName" . }}-crt
      volumes:
        - name: ca
          secret:
            defaultMode: 420
            secretName: {{ include "kubemod.fullname" . }}-crt-ca