apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubemod.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "kubemod.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "kubemod.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-api-kubemod-io-v1beta1-modrule
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: mmodrule.kubemod.io
  rules:
  - apiGroups:
    - api.kubemod.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modrules
  sideEffects: None
  timeoutSeconds: 5
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "kubemod.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /dragnet-webhook
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  matchPolicy: Equivalent
  name: dragnet.kubemod.io
  namespaceSelector:
    {{- toYaml .Values.webhook.namespaceSelector | nindent 4 }}
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    {{- toYaml .Values.webhook.resources | nindent 4 }}
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: kubemod-webhook-service
      namespace: kubemod-system
      path: /podbinding-webhook
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  name: podbinding.kubemod.io
  namespaceSelector:
    matchExpressions:
    - key: admission.kubemod.io/ignore
      operator: NotIn
      values:
      - "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods/binding
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10