apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubemod.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "kubemod.labels" . | nindent 4 }}
  creationTimestamp: null
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "kubemod.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-api-kubemod-io-v1beta1-modrule
  failurePolicy: Fail
  name: mmodrule.kubemod.io
  rules:
  - apiGroups:
    - api.kubemod.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modrules
  sideEffects: None
  timeoutSeconds: 5
{{- range .Values.webhooks }}
{{- template "kubemod.webhook" (merge (dict "webhook" .) $ ) }}
{{- end }}
