{{- $caInjector := "" }}
{{- range $k, $v := .Values.webhook.annotations }}
{{- if has $k (list "cert-manager.io/inject-ca-from" "cert-manager.io/inject-ca-from-secret" "cert-manager.io/allow-direct-injection") }}
{{- $caInjector = "true" }}
{{- end }}
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ include "kubemod.serviceAccountName" . }}-validating-webhook-configuration
  labels:
    {{- include "kubemod.labels" . | nindent 4 }}
  {{- with .Values.webhook.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    {{- if ne $caInjector "true" }}
    caBundle: Cg==
    {{- end }}
    service:
      name: {{ include "kubemod.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-api-kubemod-io-v1beta1-modrule
  failurePolicy: Fail
  name: vmodrule.kubemod.io
  rules:
  - apiGroups:
    - api.kubemod.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modrules
  sideEffects: None
  timeoutSeconds: 5